MusicApp/config/routes.rb
Rails.application.routes.draw do
  root to: 'bands#index'

  resources :users do
    get 'activate', on: :collection
  end
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :index, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :index, :create, :edit, :update, :destroy] do
    resources :notes, only: [:new]
  end

  resources :notes, only: [:show, :index, :create, :edit, :update, :destroy]
end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy if @band
    redirect_to root_url
  end

  private
  def band_params
    params[:band].permit(:name)
  end
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/views/bands/_band.html.erb
<p><%= link_to band.name, band_url(band) %></p>

MusicApp/app/views/bands/_form.html.erb
<%= render partial: 'shared/errors', locals: {current_object: @band} %>

<form action=<%= current_action %> method='post'>
  <input type='hidden'
         name='_method'
         value=<%= current_method %>>
  <%= auth_token %>

  <p>
    <label for='band_name'>Band Name:</label>
    <input type="string"
           name='band[name]'
           value=<%= @band.name %>
           id='band_name'>
  </p>

  <p>
    <input type="submit" value=<%= add_or_update %>>
  </p>

</form>

MusicApp/app/views/bands/edit.html.erb
<h1>Update Band</h1>

<%= render partial: "form",
  locals: {
    current_action: band_url(@band),
    current_method: 'patch',
    add_or_update: 'Update Band'} %>

MusicApp/app/views/bands/index.html.erb
<h1>Bands</h1>
<h3><%= link_to "Go to Albums", albums_url %></h3>
<h3><%= link_to "Go to Tracks", tracks_url %></h3>

<p>
  <%= render @bands %>
  <%= link_to "Add Band", new_band_url %>
</p>

MusicApp/app/views/bands/new.html.erb
<h1>Add a new Band</h1>

<%= render partial: "form",
  locals: {
    current_action: bands_url,
    current_method: 'post',
    add_or_update: 'Add Band'} %>

MusicApp/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<%= link_to "Edit Band", edit_band_url %>
<br>
<%= link_to "Back to Bands", bands_url %>

<h3>Albums</h3>
<% @band.albums.each do |album| %>
  <p> <%= link_to "#{album.name}", album_url(album) %></p>
<% end %>
<%= link_to "Add Album", new_band_album_url(@band) %>

<%= button_to "delete band", band_url(@band), action: 'delete', method: :delete %>