MusicApp/config/routes.rb
Rails.application.routes.draw do
  root to: 'bands#index'

  resources :users do
    get 'activate', on: :collection
  end
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :index, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :index, :create, :edit, :update, :destroy] do
    resources :notes, only: [:new]
  end

  resources :notes, only: [:show, :index, :create, :edit, :update, :destroy]
end

MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  album_id   :integer          not null
#  track_type :string           not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  TRACK_TYPES = ["regular", "bonus"]
  
  validates :name, :track_type, :album_id, presence: true
  validates :track_type, inclusion: TRACK_TYPES

  belongs_to :album
  has_one :band, through: :album

  has_many :notes
end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
    @album = @track.album
    @notes = @track.notes
  end

  def new
    @track = Track.new(album_id: params[:album_id])
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy if @track
    redirect_to album_url(@track.album)
  end

  private
  def track_params
    params[:track].permit(:name, :album_id, :lyrics, :track_type)
  end
end

MusicApp/app/helpers/tracks_helper.rb
include ERB::Util
module TracksHelper

  def ugly_lyrics(lyrics)
    lyrics = lyrics.split("\n")
    html = ""
    lyrics.each do |lyric|
      html += "<pre>#{h('♫ ' + lyric)}</pre>"
    end
    html.html_safe
  end
end

MusicApp/app/views/tracks/_form.html.erb
<%= render partial: 'shared/errors', locals: {current_object: @track} %>

<form action=<%= current_action %> method='post'>
  <input type='hidden' name='_method' value=<%= current_method %>>
  <%= auth_token %>

  <p>
    <label for='track_name'>Track Name:</label>
    <input type="string"
           name='track[name]'
           value=<%= @track.name %>
           id='track_name'>
  </p>

  <p>
    <label for='album_id'>Album:</label>
    <select name='track[album_id]' %> id='album_id'>
      <% Album.all.each do |album| %>
        <option
          value=<%= album.id %>
          <%= 'selected' if @track.album_id == album.id %>
           ><%= album.name %></option>
      <% end %>
    </select>
  </p>

  <p>
    <label for='track_type'>Track Type</label>
    <br>
    <label>Studio:</label>
    <input type="radio"
           name='track[track_type]'
           value='regular'
           <%= "checked" if @track.track_type == 'regular' %>
           id='track_type'>
    <br>
    <label>Live:</label>
    <input type="radio"
           name='track[track_type]'
           value='bonus'
           <%= "checked" if @track.track_type == 'bonus' %>
           id='track_type'>
  </p>

  <p>
    <label for='lyrics'>Lyrics:</label>
    <br>
    <textarea name='track[lyrics]' id='lyrics'><%=@track.lyrics %></textarea>
  </p>

  <p>
    <input type="submit" value=<%= add_or_update %>>
  </p>

</form>

MusicApp/app/views/tracks/_track.html.erb
<p><%= link_to track.name, track_url(track) %></p>

MusicApp/app/views/tracks/edit.html.erb
<h1>Update Track</h1>

<%= render partial: "form",
  locals: {
    current_action: track_url(@track),
    current_method: 'patch',
    add_or_update: 'Update Track'} %>

MusicApp/app/views/tracks/index.html.erb
<h1>Tracks</h1>
<h3><%= link_to "Go To Bands", bands_url %></h3>
<h3><%= link_to "Go to Albums", albums_url %></h3>
<%= render @tracks %>

MusicApp/app/views/tracks/new.html.erb
<h1>Add a new Track</h1>

<%= render partial: "form",
  locals: {
    current_action: tracks_url,
    current_method: 'post',
    add_or_update: 'Add Track'} %>

MusicApp/app/views/tracks/show.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <div><%= message %></div>
  <% end %>
<% end %>

<h1><%= @track.name %></h1>
<%= link_to "Edit Track", edit_track_url(@track) %>
<%= link_to "Back to #{@album.name}", album_url(@album) %>
<%= button_to "delete track", track_url(@track), action: 'delete', method: :delete %>

<h4>Track Type:</h4>
<p> <%= h(@track.track_type) %></p>

<h4>Lyrics:</h4>
<p><%= ugly_lyrics(@track.lyrics) %></p>

<h4>Notes:</h4>
<%= render @notes %>

<%= render partial: 'notes/form', locals: {track_id: params[:id]} %>