MusicApp/config/routes.rb
Rails.application.routes.draw do
  root to: 'bands#index'

  resources :users do
    get 'activate', on: :collection
  end
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :index, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :index, :create, :edit, :update, :destroy] do
    resources :notes, only: [:new]
  end

  resources :notes, only: [:show, :index, :create, :edit, :update, :destroy]
end

MusicApp/app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  track_id   :integer          not null
#  note       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Note < ActiveRecord::Base
  validates :note, :user_id, :track_id, presence: true

  belongs_to :user
  belongs_to :track
end

MusicApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @track = @note.track

    if @note.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @note.errors.full_messages
      redirect_to track_url(@track)
    end
  end

  def destroy
    @note = Note.find(params[:id])

    if @note && @note.user_id == current_user.id
      @track = @note.track
      @note.destroy
      redirect_to track_url(@track)
    else
      render text: "403 FORBIDDEN", status: 403
    end

  end

  private
  def note_params
    params[:note].permit(:note, :track_id)
  end

end

MusicApp/app/helpers/notes_helper.rb
module NotesHelper
end

MusicApp/app/views/notes/_form.html.erb
<h4>Add a new note!</h4>
<form action=<%= notes_url %> method='post'>
  <%= auth_token %>
  <textarea name='note[note]'></textarea>

  <input type='hidden' name='note[track_id]' value=<%= track_id %>>
  <input type='submit' value='create note'>
</form>

MusicApp/app/views/notes/_note.html.erb
Note by <%= note.user.email %>
<br>
<%= note.note %>
<%= button_to "delete note", note_url(note), action: 'delete', method: :delete %>
<br>
<br>

MusicApp/app/views/notes/new.html.erb
<%= render 'form' %>