MusicApp/config/routes.rb
Rails.application.routes.draw do
  root to: 'bands#index'

  resources :users do
    get 'activate', on: :collection
  end
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :index, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :index, :create, :edit, :update, :destroy] do
    resources :notes, only: [:new]
  end

  resources :notes, only: [:show, :index, :create, :edit, :update, :destroy]
end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  recording_type :string           not null
#  band_id        :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Album < ActiveRecord::Base
  RECORDING_TYPES = ["studio", "live"]
  
  validates :name, :recording_type, :band_id, presence: true
  validates :recording_type, inclusion: RECORDING_TYPES

  belongs_to :band

  has_many :tracks, dependent: :destroy
end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @band = @album.band
    @tracks = @album.tracks
  end

  def new
    @album = Album.new(band_id: params[:band_id])
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy if @album
    redirect_to root_url
  end

  private
  def album_params
    params[:album].permit(:name, :recording_type, :band_id)
  end
end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/views/albums/_album.html.erb
<p><%= link_to album.name, album_url(album) %></p>

MusicApp/app/views/albums/_form.html.erb
<%= render partial: 'shared/errors', locals: {current_object: @album} %>
<form action=<%= current_action %> method='post'>
  <input type='hidden' name='_method' value=<%= current_method %>>
  <%= auth_token %>

  <p>
    <label for='album_name'>Album Name:</label>
    <input type="string"
           name='album[name]'
           value=<%= @album.name %>
           id='album_name'>
  </p>

  <p>
    <label for='band_id'>Band:</label>
    <select name='album[band_id]' %> id='band_id'>
      <% Band.all.each do |band| %>
        <option
          value=<%= band.id %>
          <%= 'selected' if @album.band_id == band.id %>
           ><%= band.name %></option>
      <% end %>
    </select>
  </p>

  <p>
    <label for='recording_type'>Recording Type</label>
    <br>
    <label>Studio:</label>
    <input type="radio"
           name='album[recording_type]'
           value='studio' checked
           id='recording_type'>
    <br>
    <label>Live:</label>
    <input type="radio"
           name='album[recording_type]'
           value='live'
           id='recording_type'>
  </p>

  <p>
    <input type="submit" value=<%= add_or_update %>>
  </p>

</form>

MusicApp/app/views/albums/edit.html.erb
<h1>Update Album</h1>

<%= render partial: "form",
  locals: {
    current_action: album_url(@album),
    current_method: 'patch',
    add_or_update: 'Update Album'} %>

MusicApp/app/views/albums/index.html.erb
<h1>Albums</h1>
<h3><%= link_to "Go To Bands", bands_url %></h3>
<h3><%= link_to "Go to Tracks", tracks_url %></h3>
<%= render partial: "album", collection: @albums, as: :album %>

MusicApp/app/views/albums/new.html.erb
<h1>Add a new Album</h1>

<%= render partial: "form",
  locals: {
    current_action: albums_url,
    current_method: 'post',
    add_or_update: 'Add Album'} %>

MusicApp/app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<%= link_to "Edit Album", edit_album_url(@album) %>
<%= link_to "Back to #{@band.name}", band_url(@band) %>

<h3>Tracks:</h3>
<%= render @tracks %>
<%= link_to "Add New Track", new_album_track_url(@album) %>

<p>
  <%= button_to "delete album", album_url(@album), action: 'delete', method: :delete %>
</p>